// strings for UI language
const strings = {
  cs: {
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-cs.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-cs.svg">',
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Citovat stránku",
  	'coll-print_export': "Tisk/export",
  	'cx-campaign-contributionsmenu-mytranslations': "Překlady",
  	'cx-campaign-contributionsmenu-myuploads': "Načtené soubory",
  	'mainpage-description': "Hlavní strana",
  	'nstab-main': "Článek",
  	'pageinfo-toolboxlink': "Informace o stránce",
  	'pt-createaccount': "Vytvoření účtu",
  	'pt-login': "Přihlášení",
  	'pt-userlogout': "Odhlásit se",
  	'recentchangeslinked-toolbox': "Související změny",
  	'sandboxlink-portlet-label': "Pískoviště",
  	'searchsuggest-search': "Hledat na Wikipedii",
  	'skin-view-history': "Zobrazit historii",
  	'skin-view-view': "Číst",
  	'vector-anon-user-menu-pages': "Stránky pro odhlášené editory",
  	'vector-languages': "Jazyky",
  	'visualeditor-ca-editsource': "Editovat zdroj",
  	'wikibase-dataitem': "Položka Wikidat",
  	'wikibase-editlinkstitle': "Editovat mezijazykové odkazy",
  	'wikibase-otherprojects': "Na jiných projektech",
  	aboutsite: "O Wikipedii",
  	contactpage: "Kontaktní stránka",
  	contents: undefined,
  	currentevents: "Aktuality",
  	delete: "Smazat",
  	edit: "Editovat",
  	help: "Nápověda",
  	introduction: undefined,
  	move: "Přesunout",
  	mycontribs: "Příspěvky",
  	mypreferences: "Nastavení",
  	mytalk: "Diskuse",
  	permalink: "Trvalý odkaz",
  	portal: "Komunitní portál",
  	printableversion: "Verze k tisku",
  	purge: "Vyprázdnit cache",
  	randompage: "Náhodný článek",
  	recentchanges: "Poslední změny",
  	searchbutton: "Hledat",
  	sitesupport: "Podpořte Wikipedii",
  	specialpages: "Speciální stránky",
  	tagline: "Z Wikipedie, otevřené encyklopedie",
  	talk: "Diskuse",
  	toc: "Obsah",
  	toolbox: "Nástroje",
  	upload: "Načíst soubor",
  	whatlinkshere: "Odkazuje sem",
    collapseMenu: "Sbalit nabídku",
    pinMenuToSidebar: "Připnout na postranní panel",
    advancedTools: "Pokročilé nástroje",
    username: "Název_1993",
    modal: "<b>Připomenutí</b>: toto je prototyp. Většina věcí nefunguje. Některé části rozhraní nemusí být přeloženy do vašeho místního jazyka. Zaměřte prosím svou pozornost a zpětnou vazbu na oblasti rozhraní, kterých se otázky týkají. Pokud se obsah stránky nenačítá, obnovte stránku. Děkuji vám za Váš čas : )",
    downloadPDF: 'Stáhnout jako PDF'
  },
  de: {
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Artikel zitieren",
  	'coll-print_export': "Drucken/­exportieren",
  	'cx-campaign-contributionsmenu-mytranslations': "Übersetzungen",
  	'cx-campaign-contributionsmenu-myuploads': "Hochgeladene Medien",
  	'mainpage-description': "Hauptseite",
  	'nstab-main': "Artikel",
  	'pageinfo-toolboxlink': "Seiten­informationen",
  	'pt-createaccount': "Benutzerkonto erstellen",
  	'pt-login': "Anmelden",
  	'pt-userlogout': "Abmelden",
  	'recentchangeslinked-toolbox': "Änderungen an verlinkten Seiten",
  	'sandboxlink-portlet-label': "Spielwiese",
  	'searchsuggest-search': "Wikipedia durchsuchen",
  	'skin-view-history': "Versionsgeschichte",
  	'skin-view-view': "Lesen",
  	'vector-anon-user-menu-pages': "Seiten für abgemeldete Benutzer",
  	'vector-languages': "Sprachen",
  	'visualeditor-ca-editsource': "Quelltext bearbeiten",
  	'wikibase-dataitem': "Wikidata-Datenobjekt",
  	'wikibase-editlinkstitle': "Links auf Artikel in anderen Sprachen bearbeiten",
  	'wikibase-otherprojects': "In anderen Projekten",
  	aboutsite: "Über Wikipedia",
  	contactpage: "Kontaktseite",
  	contents: undefined,
  	currentevents: "Aktuelle Ereignisse",
  	delete: "Löschen",
  	edit: "Seite bearbeiten",
  	help: "Hilfe",
  	introduction: "Einführung",
  	move: "Verschieben",
  	mycontribs: "Beiträge",
  	mypreferences: "Einstellungen",
  	mytalk: "Diskussion",
  	permalink: "Permanenter Link",
  	portal: "Autorenportal",
  	printableversion: "Druckversion",
  	purge: "Cache leeren",
  	randompage: "Zufälliger Artikel",
  	recentchanges: "Letzte Änderungen",
  	searchbutton: "Suchen",
  	sitesupport: "Spenden",
  	specialpages: "Spezialseiten",
  	tagline: "aus Wikipedia, der freien Enzyklopädie",
  	talk: "Diskussion",
  	toc: "Inhaltsverzeichnis",
  	toolbox: "Werkzeuge",
  	upload: "Datei hochladen",
  	whatlinkshere: "Links auf diese Seite",
    collapseMenu: 'Menü minimieren',
    pinMenuToSidebar: 'Menü an die Seitenleiste anheften',
    advancedTools: 'Erweiterte Tools',
    username: 'name_1993',
    logo: '<img src="/img/logo-es.svg" />',
    modal:'<b>Zur Erinnerung</b>: Dies ist ein Prototyp. Die meisten Dinge funktionieren nicht. Einige Teile der Benutzeroberfläche sind möglicherweise nicht in Ihre Landessprache übersetzt. Bitte konzentrieren Sie Ihre Aufmerksamkeit und Ihr Feedback auf die Bereiche der Benutzeroberfläche, zu denen die Fragen gestellt werden. Wenn der Seiteninhalt nicht geladen wird, aktualisieren Sie bitte die Seite. Vielen Dank für Ihre Zeit : )',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-de.svg">',
    downloadPDF: 'Als PDF herunterladen'
  },
  en: {
    talk: 'Talk',
    'vector-languages': '95 languages'
  },
  es: {
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Citar esta página",
  	'coll-print_export': "Imprimir/exportar",
  	'cx-campaign-contributionsmenu-mytranslations': "Traducciones",
  	'cx-campaign-contributionsmenu-myuploads': "Archivos subidos",
  	'mainpage-description': "Portada",
  	'nstab-main': "Artículo",
  	'pageinfo-toolboxlink': "Información de la página",
  	'pt-createaccount': "Crear una cuenta",
  	'pt-login': "Acceder",
  	'pt-userlogout': "Salir",
  	'recentchangeslinked-toolbox': "Cambios en enlazadas",
  	'sandboxlink-portlet-label': "Taller",
  	'searchsuggest-search': "Buscar en Wikipedia",
  	'skin-view-history': "Ver historial",
  	'skin-view-view': "Leer",
  	'vector-anon-user-menu-pages': "Páginas para editores desconectados",
  	'vector-languages': "Idiomas",
  	'visualeditor-ca-editsource': "Editar código",
  	'wikibase-dataitem': "Elemento de Wikidata",
  	'wikibase-editlinkstitle': "Editar enlaces interlingüísticos",
  	'wikibase-otherprojects': "En otros proyectos",
  	aboutsite: "Acerca de Wikipedia",
  	contactpage: "Página de contacto",
  	contents: undefined,
  	currentevents: "Actualidad",
  	delete: "Borrar",
  	edit: "Editar",
  	help: "Ayuda",
  	introduction: undefined,
  	move: "Trasladar",
  	mycontribs: "Contribuciones",
  	mypreferences: "Preferencias",
  	mytalk: "Discusión",
  	permalink: "Enlace permanente",
  	portal: "Portal de la comunidad",
  	printableversion: "Versión para imprimir",
  	purge: "Purgar",
  	randompage: "Página aleatoria",
  	recentchanges: "Cambios recientes",
  	searchbutton: "Buscar",
  	sitesupport: "Donaciones",
  	specialpages: "Páginas especiales",
  	tagline: "De Wikipedia, la enciclopedia libre",
  	talk: "Discusión",
  	toc: "Índice",
  	toolbox: "Herramientas",
  	upload: "Subir archivo",
  	whatlinkshere: "Lo que enlaza aquí",
    collapseMenu: 'Ocultar menú',
    pinMenuToSidebar: 'Anclar menú a la barra lateral',
    advancedTools: 'Herramientas avanzadas',
    username: 'nombre_1993',
    logo: '<img src="/img/logo-es.svg" />',
    modal:'<b>Recordatorio</b>: este es un prototipo. La mayoría de las cosas no funcionan. Es posible que algunas partes de la interfaz no estén traducidas a su idioma local. Concentre su atención y sus comentarios en las áreas de la interfaz sobre las que se refieren las preguntas. Si el contenido de la página no se carga, actualice la página. Gracias por tu tiempo : )',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-es.svg">',
    downloadPDF: 'Descargar como PDF'
  },
  fi: {
    'betafeatures-toplink': "Beeta",
  	'citethispage-link': "Viitetiedot",
  	'coll-print_export': "Tulosta/vie",
  	'cx-campaign-contributionsmenu-mytranslations': "Käännökset",
  	'cx-campaign-contributionsmenu-myuploads': "Tallennettu aineisto",
  	'mainpage-description': "Etusivu",
  	'nstab-main': "Artikkeli",
  	'pageinfo-toolboxlink': "Sivun tiedot",
  	'pt-createaccount': "Luo tunnus",
  	'pt-login': "Kirjaudu sisään",
  	'pt-userlogout': "Kirjaudu ulos",
  	'recentchangeslinked-toolbox': "Linkitettyjen sivujen muutokset",
  	'sandboxlink-portlet-label': "Hiekkalaatikko",
  	'searchsuggest-search': "Hae Wikipediasta",
  	'skin-view-history': "Näytä historia",
  	'skin-view-view': "Lue",
  	'vector-anon-user-menu-pages': "Sivut kirjautumattomille muokkaajille",
  	'vector-languages': "Kielet",
  	'visualeditor-ca-editsource': "Muokkaa wikitekstiä",
  	'wikibase-dataitem': "Wikidata-kohde",
  	'wikibase-editlinkstitle': "Muokkaa kieltenvälisiä linkkejä",
  	'wikibase-otherprojects': "Muissa hankkeissa",
  	aboutsite: "Tietoja Wikipediasta",
  	contactpage: "Yhteydenottosivu",
  	contents: undefined,
  	currentevents: "Ajankohtaista",
  	delete: "Poista",
  	edit: "Muokkaa",
  	help: "Ohje",
  	introduction: undefined,
  	move: "Siirrä",
  	mycontribs: "Muokkaukset",
  	mypreferences: "Asetukset",
  	mytalk: "Keskustelu",
  	permalink: "Ikilinkki",
  	portal: "Kahvihuone",
  	printableversion: "Tulostettava versio",
  	purge: "Tyhjennä välimuisti",
  	randompage: "Satunnainen artikkeli",
  	recentchanges: "Tuoreet muutokset",
  	searchbutton: "Hae",
  	sitesupport: "Lahjoitukset",
  	specialpages: "Toimintosivut",
  	tagline: "",
  	talk: "Keskustelu",
  	toc: "Sisällys",
  	toolbox: "Työkalut",
  	upload: "Tallenna tiedosto",
  	whatlinkshere: "Tänne viittaavat sivut",
    collapseMenu: "Tiivistä valikko",
    pinMenuToSidebar: "Kiinnitä sivupalkkiin",
    advancedTools: "Edistyneet työkalut",
    username: "Nimi_1993",
    modal: "<b>Muistutus</b>: tämä on prototyyppi. Useimmat asiat eivät toimi. Joitakin käyttöliittymän osia ei ehkä ole käännetty paikalliselle kielellesi. Keskitä huomiosi ja palautteesi niihin käyttöliittymän alueisiin, joita kysymykset koskevat. Jos sivun sisältö ei lataudu, päivitä sivu. Kiitos ajastasi : )",
    taglineImg: '<img id="tagline" src="/img/logos/tagline-fi.svg">',
    downloadPDF: 'Lataa PDF-tiedostona'
  },
  fr: {
    'betafeatures-toplink': "Bêta",
  	'citethispage-link': "Citer cette page",
  	'coll-print_export': "Imprimer / exporter",
  	'cx-campaign-contributionsmenu-mytranslations': "Traductions",
  	'cx-campaign-contributionsmenu-myuploads': "Fichiers téléversés",
  	'mainpage-description': "Accueil",
  	'nstab-main': "Article",
  	'pageinfo-toolboxlink': "Informations sur la page",
  	'pt-createaccount': "Créer un compte",
  	'pt-login': "Se connecter",
  	'pt-userlogout': "Se déconnecter",
  	'recentchangeslinked-toolbox': "Suivi des pages liées",
  	'sandboxlink-portlet-label': "Brouillon",
  	'searchsuggest-search': "Rechercher sur Wikipédia",
  	'skin-view-history': "Voir l’historique",
  	'skin-view-view': "Lire",
  	'vector-anon-user-menu-pages': "Pages pour les contributeurs déconnectés",
  	'vector-languages': "Langues",
  	'visualeditor-ca-editsource': "Modifier le code",
  	'wikibase-dataitem': "Élément Wikidata",
  	'wikibase-editlinkstitle': "Modifier les liens interlangues",
  	'wikibase-otherprojects': "Dans d’autres projets",
  	aboutsite: "À propos de Wikipédia",
  	contactpage: "Page de contact",
  	contents: undefined,
  	currentevents: "Actualités",
  	delete: "Supprimer",
  	edit: "Modifier",
  	help: "Aide",
  	introduction: undefined,
  	move: "Renommer",
  	mycontribs: "Contributions",
  	mypreferences: "Préférences",
  	mytalk: "Discussion",
  	permalink: "Lien permanent",
  	portal: "Communauté",
  	printableversion: "Version imprimable",
  	purge: "Purger",
  	randompage: "Article au hasard",
  	recentchanges: "Modifications récentes",
  	searchbutton: "Rechercher",
  	sitesupport: "Faire un don",
  	specialpages: "Pages spéciales",
  	tagline: "Un article de Wikipédia, l'encyclopédie libre.",
  	talk: "Discussion",
  	toc: "Sommaire",
  	toolbox: "Outils",
  	upload: "Téléverser un fichier",
  	whatlinkshere: "Pages liées",
    collapseMenu: "Réduire le menu",
    pinMenuToSidebar: "Épingler à la barre latérale",
    advancedTools: "Outils avancés",
    username: "Nom_1993",
    modal: "<b>Rappel</b>: il s'agit d'un prototype. La plupart des choses ne fonctionnent pas. Certaines parties de l'interface peuvent ne pas être traduites dans votre langue locale. Veuillez concentrer votre attention et vos commentaires sur les zones de l'interface sur lesquelles portent les questions. Si le contenu de la page ne se charge pas, veuillez actualiser la page. Merci pour votre temps : )",
    taglineImg: '<img id="tagline" src="/img/logos/wordmark-fr.svg">',
    downloadPDF: 'Télécharger comme PDF'
  },
  it: {
    taglineImg: '<img id="tagline" src="/img/logos/tagline-it.svg">',
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Cita questa voce",
  	'coll-print_export': "Stampa/esporta",
  	'cx-campaign-contributionsmenu-mytranslations': "Traduzioni",
  	'cx-campaign-contributionsmenu-myuploads': "File multimediali caricati",
  	'mainpage-description': "Pagina principale",
  	'nstab-main': "Voce",
  	'pageinfo-toolboxlink': "Informazioni pagina",
  	'pt-createaccount': "Registrati",
  	'pt-login': "Entra",
  	'pt-userlogout': "Esci",
  	'recentchangeslinked-toolbox': "Modifiche correlate",
  	'sandboxlink-portlet-label': "Prove",
  	'searchsuggest-search': "Cerca in Wikipedia",
  	'skin-view-history': "Cronologia",
  	'skin-view-view': "Leggi",
  	'vector-anon-user-menu-pages': "Pagine per utenti anonimi",
  	'vector-languages': "Lingue",
  	'visualeditor-ca-editsource': "Modifica wikitesto",
  	'wikibase-dataitem': "Elemento Wikidata",
  	'wikibase-editlinkstitle': "Modifica collegamenti interlinguistici",
  	'wikibase-otherprojects': "In altri progetti",
  	aboutsite: "Informazioni su Wikipedia",
  	contactpage: "Contatti",
  	contents: undefined,
  	currentevents: "Attualità",
  	delete: "Cancella",
  	edit: "Modifica",
  	help: "Aiuto",
  	introduction: "Introduzione",
  	move: "Sposta",
  	mycontribs: "Contributi",
  	mypreferences: "Preferenze",
  	mytalk: "Discussioni",
  	permalink: "Link permanente",
  	portal: "Portale Comunità",
  	printableversion: "Versione stampabile",
  	purge: "Purga",
  	randompage: "Una voce a caso",
  	recentchanges: "Ultime modifiche",
  	searchbutton: "Ricerca",
  	sitesupport: "Fai una donazione",
  	specialpages: "Pagine speciali",
  	tagline: "Da Wikipedia, l'enciclopedia libera.",
  	talk: "Discussione",
  	toc: "Indice",
  	toolbox: "Strumenti",
  	upload: "Carica un file",
  	whatlinkshere: "Puntano qui",
    collapseMenu: "Riduci menu",
    pinMenuToSidebar: "Aggiungi il menu alla barra laterale",
    advancedTools: "Strumenti avanzati",
    username: "Nome_1993",
    modal: "<b>Promemoria</b>: questo è un prototipo. La maggior parte delle cose non funziona. Alcune parti dell'interfaccia potrebbero non essere tradotte nella tua lingua locale. Per favore concentra la tua attenzione e il tuo feedback sulle aree dell'interfaccia su cui si pongono le domande. Se il contenuto della pagina non viene caricato, aggiorna la pagina. Grazie per il tuo tempo : )",
    downloadPDF: 'Scarica come PDF'
  },
  id: {

  },
  ja: {
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-ja.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-ja.svg">',
    'betafeatures-toplink': "ベータ版",
  	'citethispage-link': "このページを引用",
  	'coll-print_export': "印刷/書き出し",
  	'cx-campaign-contributionsmenu-mytranslations': "翻訳",
  	'cx-campaign-contributionsmenu-myuploads': "アップロードされたメディア",
  	'mainpage-description': "メインページ",
  	'nstab-main': "ページ",
  	'pageinfo-toolboxlink': "ページ情報",
  	'pt-createaccount': "アカウント作成",
  	'pt-login': "ログイン",
  	'pt-userlogout': "ログアウト",
  	'recentchangeslinked-toolbox': "関連ページの更新状況",
  	'sandboxlink-portlet-label': "下書き",
  	'searchsuggest-search': "Wikipedia 内を検索",
  	'skin-view-history': "履歴表示",
  	'skin-view-view': "閲覧",
  	'vector-anon-user-menu-pages': "ログアウトした編集者のページ",
  	'vector-languages': "言語",
  	'visualeditor-ca-editsource': "ソースを編集",
  	'wikibase-dataitem': "Wikidata 項目",
  	'wikibase-editlinkstitle': "言語間リンクを編集する",
  	'wikibase-otherprojects': "他のプロジェクト",
  	aboutsite: "ウィキペディアについて",
  	contactpage: "連絡先",
  	contents: undefined,
  	currentevents: "最近の出来事",
  	delete: "削除",
  	edit: "編集",
  	help: "ヘルプ",
  	introduction: "序章",
  	move: "移動",
  	mycontribs: "投稿記録",
  	mypreferences: "個人設定",
  	mytalk: "会話",
  	permalink: "この版への固定リンク",
  	portal: "コミュニティ・ポータル",
  	printableversion: "印刷用バージョン",
  	purge: "キャッシュを削除",
  	randompage: "おまかせ表示",
  	recentchanges: "最近の更新",
  	searchbutton: "検索",
  	sitesupport: "寄付",
  	specialpages: "特別ページ",
  	tagline: "{{#ifeq: {{NAMESPACENUMBER}},| 0 | 出典: フリー百科事典『ウィキペディア（Wikipedia）』,| }}",
  	talk: "ノート",
  	toc: "目次",
  	toolbox: "ツール",
  	upload: "ファイルをアップロード",
  	whatlinkshere: "リンク元",
    collapseMenu: 'メニューを折りたたむ',
    pinMenuToSidebar: 'メニューをサイドバーに固定する',
    advancedTools: '高度なツール',
    username: '名前_1993',
    logo: '<img src="/img/logo-es.svg" />',
    modal:'<b>注意</b>：これはプロトタイプです。 ほとんどのものは機能しません。 インターフェイスの一部がローカル言語に翻訳されていない可能性があります。 ページのコンテンツが読み込まれていない場合は、ページを更新してください。 お時間をいただきありがとうございます : )',
    downloadPDF: '下载为PDF'
  },
  ko: {
    'betafeatures-toplink': "베타",
  	'citethispage-link': "이 문서 인용하기",
  	'coll-print_export': "인쇄/내보내기",
  	'cx-campaign-contributionsmenu-mytranslations': "번역",
  	'cx-campaign-contributionsmenu-myuploads': "올린 미디어",
  	'mainpage-description': "대문",
  	'nstab-main': "문서",
  	'pageinfo-toolboxlink': "문서 정보",
  	'pt-createaccount': "계정 만들기",
  	'pt-login': "로그인",
  	'pt-userlogout': "로그아웃",
  	'recentchangeslinked-toolbox': "가리키는 글의 최근 바뀜",
  	'sandboxlink-portlet-label': "연습장",
  	'searchsuggest-search': "위키백과 검색",
  	'skin-view-history': "역사 보기",
  	'skin-view-view': "읽기",
  	'vector-anon-user-menu-pages': "로그아웃한 편집자를 위한 문서",
  	'vector-languages': "언어",
  	'visualeditor-ca-editsource': "원본 편집",
  	'wikibase-dataitem': "위키데이터 항목",
  	'wikibase-editlinkstitle': "언어 간 링크 편집",
  	'wikibase-otherprojects': "다른 프로젝트",
  	aboutsite: "위키백과 소개",
  	contactpage: "연락 문서",
  	contents: "내용물",
  	currentevents: "요즘 화제",
  	delete: "삭제",
  	edit: "편집",
  	help: "도움말",
  	introduction: undefined,
  	move: "이동",
  	mycontribs: "기여",
  	mypreferences: "환경 설정",
  	mytalk: "토론",
  	permalink: "고유 링크",
  	portal: "사용자 모임",
  	printableversion: "인쇄용 판",
  	purge: "새로 고침",
  	randompage: "임의의 문서로",
  	recentchanges: "최근 바뀜",
  	searchbutton: "검색",
  	sitesupport: "기부",
  	specialpages: "특수 문서 목록",
  	tagline: "위키백과, 우리 모두의 백과사전.",
  	talk: "토론",
  	toc: "목차",
  	toolbox: "도구",
  	upload: "파일 올리기",
  	whatlinkshere: "여기를 가리키는 문서",
    collapseMenu: "붕괴 메뉴",
    pinMenuToSidebar: "사이드 바에 핀 메뉴",
    advancedTools: "고급 도구",
    username: "이름_1993",
    downloadPDF: 'PDF로 다운로드',
    modal: "<b>알림</b>: 이것은 프로토 타입입니다. 대부분의 것들은 작동하지 않습니다. 인터페이스의 일부 부분은 해당 지역 언어로 번역되지 않을 수 있습니다. 질문이 묻는 인터페이스의 영역에 대한 관심과 의견을 집중하십시오. 페이지 내용이로드되지 않은 경우 페이지를 새로 고치십시오. 시간 내 주셔서 감사합니다 : )",
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-ko.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-ko.svg">'
  },
  nl: {
    taglineImg: '<img id="tagline" src="/img/logos/tagline-nl.svg">',
    'betafeatures-toplink': "Bèta",
  	'citethispage-link': "Deze pagina citeren",
  	'coll-print_export': "Afdrukken/exporteren",
  	'cx-campaign-contributionsmenu-mytranslations': "Vertalingen",
  	'cx-campaign-contributionsmenu-myuploads': "Geüploade media",
  	'mainpage-description': "Hoofdpagina",
  	'nstab-main': "Artikel",
  	'pageinfo-toolboxlink': "Paginagegevens",
  	'pt-createaccount': "Account aanmaken",
  	'pt-login': "Inloggen",
  	'pt-userlogout': "Afmelden",
  	'recentchangeslinked-toolbox': "Gerelateerde wijzigingen",
  	'sandboxlink-portlet-label': "Kladblok",
  	'searchsuggest-search': "Doorzoek Wikipedia",
  	'skin-view-history': "Geschiedenis weergeven",
  	'skin-view-view': "Lezen",
  	'vector-anon-user-menu-pages': "Pagina's voor uitgelogde redacteuren",
  	'vector-languages': "Talen",
  	'visualeditor-ca-editsource': "Brontekst bewerken",
  	'wikibase-dataitem': "Wikidata-item",
  	'wikibase-editlinkstitle': "Koppelingen tussen talen bewerken",
  	'wikibase-otherprojects': "In andere projecten",
  	aboutsite: "Over Wikipedia",
  	contactpage: "Contactpagina",
  	contents: undefined,
  	currentevents: "Actuele gebeurtenissen",
  	delete: "Verwijderen",
  	edit: "Bewerken",
  	help: "Hulp en contact",
  	introduction: undefined,
  	move: "Titel wijzigen",
  	mycontribs: "Bijdragen",
  	mypreferences: "Voorkeuren",
  	mytalk: "Overleg",
  	permalink: "Permanente koppeling",
  	portal: "Gebruikersportaal",
  	printableversion: "Printvriendelijke versie",
  	purge: "Cache legen",
  	randompage: "Willekeurige pagina",
  	recentchanges: "Recente wijzigingen",
  	searchbutton: "Zoeken",
  	sitesupport: "Doneren",
  	specialpages: "Speciale pagina's",
  	tagline: "Uit Wikipedia, de vrije encyclopedie",
  	talk: "Overleg",
  	toc: "Inhoud",
  	toolbox: "Hulpmiddelen",
  	upload: "Bestand uploaden",
  	whatlinkshere: "Links naar deze pagina",
    collapseMenu: "Menu samenvouwen",
    pinMenuToSidebar: "Menu vastzetten aan zijbalk",
    advancedTools: "Geavanceerd gereedschap",
    username: "Naam_1993",
    modal: "<b>Ter herinnering</b>: dit is een prototype. De meeste dingen werken niet. Sommige delen van de interface zijn mogelijk niet vertaald in uw lokale taal. Richt uw aandacht en uw feedback op de delen van de interface waar de vragen over gaan. Als de pagina-inhoud niet laadt, ververs dan de pagina. Bedankt voor je tijd : )",
    downloadPDF: 'Downloaden als PDF'
  },
  pl: {
    taglineImg: '<img id="tagline" src="/img/logos/tagline-pl.svg">',
    'betafeatures-toplink': "Funkcje eksperymentalne",
  	'citethispage-link': "Cytowanie tego artykułu",
  	'coll-print_export': "Drukuj lub eksportuj",
  	'cx-campaign-contributionsmenu-mytranslations': "Tłumaczenia",
  	'cx-campaign-contributionsmenu-myuploads': "Przesłane multimedia",
  	'mainpage-description': "Strona główna",
  	'nstab-main': "Artykuł",
  	'pageinfo-toolboxlink': "Informacje o tej stronie",
  	'pt-createaccount': "Utwórz konto",
  	'pt-login': "Zaloguj się",
  	'pt-userlogout': "Wyloguj",
  	'recentchangeslinked-toolbox': "Zmiany w linkowanych",
  	'sandboxlink-portlet-label': "Brudnopis",
  	'searchsuggest-search': "Przeszukaj Wikipedię",
  	'skin-view-history': "Wyświetl historię",
  	'skin-view-view': "Czytaj",
  	'vector-anon-user-menu-pages': "Strony dla anonimowych edytorów",
  	'vector-languages': "Języki",
  	'visualeditor-ca-editsource': "Edytuj kod źródłowy",
  	'wikibase-dataitem': "Element Wikidanych",
  	'wikibase-editlinkstitle': "Edytuj linki pomiędzy wersjami językowymi",
  	'wikibase-otherprojects': "W innych projektach",
  	aboutsite: "O Wikipedię",
  	contactpage: "Kontakt",
  	contents: undefined,
  	currentevents: "Bieżące wydarzenia",
  	delete: "Usuń",
  	edit: "Edytuj",
  	help: "Pomoc",
  	introduction: undefined,
  	move: "Przenieś",
  	mycontribs: "Edycje",
  	mypreferences: "Preferencje",
  	mytalk: "Dyskusja",
  	permalink: "Link do tej wersji",
  	portal: "Portal wikipedystów",
  	printableversion: "Wersja do druku",
  	purge: "Odśwież",
  	randompage: "Losuj artykuł",
  	recentchanges: "Ostatnie zmiany",
  	searchbutton: "Szukaj",
  	sitesupport: "Wspomóż Wikipedię",
  	specialpages: "Strony specjalne",
  	tagline: "Z Wikipedię, wolnej encyklopedii",
  	talk: "Dyskusja",
  	toc: "Spis treści",
  	toolbox: "Narzędzia",
  	upload: "Prześlij plik",
  	whatlinkshere: "Linkujące",
    collapseMenu: "Zwiń menu",
    pinMenuToSidebar: "Przypnij menu do paska bocznego",
    advancedTools: "Zaawansowane narzędzia",
    username: "Imię_1993",
    modal: "<b>Przypomnienie</b>: to jest prototyp. Większość rzeczy nie działa. Niektóre części interfejsu mogą nie zostać przetłumaczone na Twój język lokalny. Skoncentruj swoją uwagę i opinie na obszarach interfejsu, których dotyczą pytania. Jeśli zawartość strony się nie ładuje, odśwież stronę. Dziękuję za Twój czas : )",
    downloadPDF: 'Pobierz jako PDF'
  },
  pt: {
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Citar esta página",
  	'coll-print_export': "Imprimir/exportar",
  	'cx-campaign-contributionsmenu-mytranslations': "Traduções",
  	'cx-campaign-contributionsmenu-myuploads': "Carregamentos",
  	'mainpage-description': "Página principal",
  	'nstab-main': "Artigo",
  	'pageinfo-toolboxlink': "Informações da página",
  	'pt-createaccount': "Criar uma conta",
  	'pt-login': "Entrar",
  	'pt-userlogout': "Sair",
  	'recentchangeslinked-toolbox': "Alterações relacionadas",
  	'sandboxlink-portlet-label': "Testes",
  	'searchsuggest-search': "Pesquisar na Wikipédia",
  	'skin-view-history': "Ver histórico",
  	'skin-view-view': "Ler",
  	'vector-anon-user-menu-pages': "Páginas para editores conectados",
  	'vector-languages': "Idiomas",
  	'visualeditor-ca-editsource': "Editar código-fonte",
  	'wikibase-dataitem': "Elemento Wikidata",
  	'wikibase-editlinkstitle': "Editar hiperligações interlínguas",
  	'wikibase-otherprojects': "Noutros projetos",
  	aboutsite: "Sobre a Wikipédia",
  	contactpage: "Página de contacto",
  	contents: undefined,
  	currentevents: "Eventos atuais",
  	delete: "Eliminar",
  	edit: "Editar",
  	help: "Ajuda",
  	introduction: undefined,
  	move: "Mover",
  	mycontribs: "Contribuições",
  	mypreferences: "Preferências",
  	mytalk: "Discussão",
  	permalink: "Hiperligação permanente",
  	portal: "Portal comunitário",
  	printableversion: "Versão para impressão",
  	purge: "Purgar",
  	randompage: "Página aleatória",
  	recentchanges: "Mudanças recentes",
  	searchbutton: "Pesquisar",
  	sitesupport: "Donativos",
  	specialpages: "Páginas especiais",
  	tagline: "Origem: Wikipédia, a enciclopédia livre.",
  	talk: "Discussão",
  	toc: "Índice",
  	toolbox: "Ferramentas",
  	upload: "Carregar ficheiro",
  	whatlinkshere: "Páginas afluentes",
    collapseMenu: "Recolher menu",
    pinMenuToSidebar: "Fixar na barra lateral",
    advancedTools: "Ferramentas avançadas",
    username: "Nome_1993",
    modal: "<b>Lembrete</b>: este é um protótipo. A maioria das coisas não funciona. Algumas partes da interface podem não ser traduzidas para seu idioma local. Concentre sua atenção e seus comentários nas áreas da interface sobre as quais as perguntas são feitas. Se o conteúdo da página não estiver carregando, atualize a página. Obrigado pelo seu tempo : )",
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-fr.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-pt.svg">',
    downloadPDF: 'Baixe como PDF'
  },
  ru: {
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-ru.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-ru.svg">',
    'betafeatures-toplink': "Бета",
  	'citethispage-link': "Цитировать страницу",
  	'coll-print_export': "Печать/экспорт",
  	'cx-campaign-contributionsmenu-mytranslations': "Переводы",
  	'cx-campaign-contributionsmenu-myuploads': "Загруженные медиафайлы",
  	'mainpage-description': "Заглавная страница",
  	'nstab-main': "Статья",
  	'pageinfo-toolboxlink': "Сведения о странице",
  	'pt-createaccount': "Создать учётную запись",
  	'pt-login': "Войти",
  	'pt-userlogout': "Выйти",
  	'recentchangeslinked-toolbox': "Связанные правки",
  	'sandboxlink-portlet-label': "Черновик",
  	'searchsuggest-search': "Искать в Википедии",
  	'skin-view-history': "История",
  	'skin-view-view': "Читать",
  	'vector-anon-user-menu-pages': "Pages for logged out editors",
  	'vector-languages': "Языки",
  	'visualeditor-ca-editsource': "Править код",
  	'wikibase-dataitem': "Элемент Wikidata",
  	'wikibase-editlinkstitle': "Править межъязыковые ссылки",
  	'wikibase-otherprojects': "В других проектах",
  	aboutsite: "Описание Википедии",
  	contactpage: "Страница контакта",
  	contents: undefined,
  	currentevents: "Текущие события",
  	delete: "Удалить",
  	edit: "Править",
  	help: "Справка",
  	introduction: "Как править статьи",
  	move: "Переименовать",
  	mycontribs: "Вклад",
  	mypreferences: "Настройки",
  	mytalk: "Обсуждение",
  	permalink: "Постоянная ссылка",
  	portal: "Сообщество",
  	printableversion: "Версия для печати",
  	purge: "Очистить кэш",
  	randompage: "Случайная статья",
  	recentchanges: "Свежие правки",
  	searchbutton: "Найти",
  	sitesupport: "Пожертвовать",
  	specialpages: "Служебные страницы",
  	tagline: "Материал из Википедии — свободной энциклопедии",
  	talk: "Обсуждение",
  	toc: "Содержание",
  	toolbox: "Инструменты",
  	upload: "Загрузить файл",
  	whatlinkshere: "Ссылки сюда",
    collapseMenu: "Свернуть меню",
    pinMenuToSidebar: "Закрепить меню на боковой панели",
    advancedTools: "Расширенные инструменты",
    username: "Имя_1993",
    modal: "<b>Напоминаю</b>: это прототип. Большинство вещей не работает. Некоторые части интерфейса могут быть не переведены на ваш местный язык. Пожалуйста, сосредоточьте свое внимание и свои отзывы на областях интерфейса, о которых говорится в вопросах. Если содержимое страницы не загружается, обновите страницу. Спасибо за уделенное время : )",
    downloadPDF: 'Скачать как PDF'
  },
  sv: {
    taglineImg: '<img id="tagline" src="/img/logos/tagline-sv.svg">',
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Använd som referens",
  	'coll-print_export': "Skriv ut/exportera",
  	'cx-campaign-contributionsmenu-mytranslations': "Översättningar",
  	'cx-campaign-contributionsmenu-myuploads': "Uppladdad media",
  	'mainpage-description': "Huvudsida",
  	'nstab-main': "Artikel",
  	'pageinfo-toolboxlink': "Sidinformation",
  	'pt-createaccount': "Skapa konto",
  	'pt-login': "Logga in",
  	'pt-userlogout': "Logga ut",
  	'recentchangeslinked-toolbox': "Relaterade ändringar",
  	'sandboxlink-portlet-label': "Sandlåda",
  	'searchsuggest-search': "Sök på Wikipedia",
  	'skin-view-history': "Visa historik",
  	'skin-view-view': "Läs",
  	'vector-anon-user-menu-pages': "Sidor för utloggade redigerade",
  	'vector-languages': "Språk",
  	'visualeditor-ca-editsource': "Redigera wikitext",
  	'wikibase-dataitem': "Wikidata-objekt",
  	'wikibase-editlinkstitle': "Redigera interwikilänkar",
  	'wikibase-otherprojects': "På andra projekt",
  	aboutsite: "Om Wikipedia",
  	contactpage: "Kontaktsida",
  	contents: undefined,
  	currentevents: "Aktuella händelser",
  	delete: "Radera",
  	edit: "Redigera",
  	help: "Hjälp",
  	introduction: undefined,
  	move: "Flytta",
  	mycontribs: "Bidrag",
  	mypreferences: "Inställningar",
  	mytalk: "Diskussion",
  	permalink: "Permanent länk",
  	portal: "Deltagarportalen",
  	printableversion: "Utskriftsvänlig version",
  	purge: "Rensa",
  	randompage: "Slumpartikel",
  	recentchanges: "Senaste ändringarna",
  	searchbutton: "Sök",
  	sitesupport: "Stöd Wikipedia",
  	specialpages: "Specialsidor",
  	tagline: "Från Wikipedia",
  	talk: "Diskussion",
  	toc: "Innehåll",
  	toolbox: "Verktyg",
  	upload: "Ladda upp fil",
  	whatlinkshere: "Sidor som länkar hit",
    collapseMenu: "Komprimera menyn",
    pinMenuToSidebar: "Fäst till sidofältet",
    advancedTools: "Avancerade verktyg",
    username: "Namn_1993",
    modal: "<b>Påminnelse</b>: detta är en prototyp. Det mesta fungerar inte. Vissa delar av gränssnittet kanske inte är översatta till ditt lokala språk. Vänligen fokusera din uppmärksamhet och din feedback på de områden i gränssnittet som frågorna ställer. Om sidans innehåll inte laddas, vänligen uppdatera sidan. Tack för din tid : )",
    downloadPDF: 'Ladda ned som PDF'
  },
  uk: {
    'betafeatures-toplink': "Бета",
  	'citethispage-link': "Цитувати сторінку",
  	'coll-print_export': "Друк/експорт",
  	'cx-campaign-contributionsmenu-mytranslations': "Переклади",
  	'cx-campaign-contributionsmenu-myuploads': "Завантажені медіафайли",
  	'mainpage-description': "Головна сторінка",
  	'nstab-main': "Стаття",
  	'pageinfo-toolboxlink': "Інформація про сторінку",
  	'pt-createaccount': "Створити обліковий запис",
  	'pt-login': "Увійти",
  	'pt-userlogout': "Вийти",
  	'recentchangeslinked-toolbox': "Пов'язані редагування",
  	'sandboxlink-portlet-label': "Чернетка",
  	'searchsuggest-search': "Пошук у Вікіпедії",
  	'skin-view-history': "Переглянути історію",
  	'skin-view-view': "Читати",
  	'vector-anon-user-menu-pages': "Сторінка для редакторів, які вийшли з системи",
  	'vector-languages': "Мови",
  	'visualeditor-ca-editsource': "Редагувати код",
  	'wikibase-dataitem': "Елемент Вікіданих",
  	'wikibase-editlinkstitle': "Редагувати міжмовні посилання",
  	'wikibase-otherprojects': "В інших проєктах",
  	aboutsite: "Про Вікіпедії",
  	contactpage: "Сторінка контакту",
  	contents: undefined,
  	currentevents: "Поточні події",
  	delete: "Видалити",
  	edit: "Редагувати",
  	help: "Довідка",
  	introduction: undefined,
  	move: "Перейменувати",
  	mycontribs: "Внесок",
  	mypreferences: "Налаштування",
  	mytalk: "Обговорення",
  	permalink: "Постійне посилання",
  	portal: "Портал спільноти",
  	printableversion: "Версія до друку",
  	purge: "Очистити",
  	randompage: "Випадкова стаття",
  	recentchanges: "Нові редагування",
  	searchbutton: "Знайти",
  	sitesupport: "Пожертвувати",
  	specialpages: "Спеціальні сторінки",
  	tagline: "Матеріал з Вікіпедії — вільної енциклопедії.",
  	talk: "Обговорення",
  	toc: "Зміст",
  	toolbox: "Інструменти",
  	upload: "Завантажити файл",
  	whatlinkshere: "Посилання сюди",
    collapseMenu: "Згорнути меню",
    pinMenuToSidebar: "Закріпити на бічній панелі",
    advancedTools: "Розширені інструменти",
    username: "Ім'я_1993",
    modal: "<b>Нагадуємо</b>: це прототип. Більшість речей не працює. Деякі частини інтерфейсу можуть не бути перекладені на вашу місцеву мову. Будь ласка, зосередьте свою увагу та відгуки на областях інтерфейсу, про які ставлять запитання. Якщо вміст сторінки не завантажується, оновіть сторінку. Спасибі за ваш час : )",
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-uk.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-uk.svg">',
    downloadPDF: 'Завантажити як PDF'
  },
  vi: {
    'betafeatures-toplink': "Beta",
  	'citethispage-link': "Trích dẫn trang này",
  	'coll-print_export': "In và xuất",
  	'cx-campaign-contributionsmenu-mytranslations': "Bản dịch",
  	'cx-campaign-contributionsmenu-myuploads': "Phương tiện tải lên",
  	'mainpage-description': "Trang Chính",
  	'nstab-main': "Bài viết",
  	'pageinfo-toolboxlink': "Thông tin trang",
  	'pt-createaccount': "Tạo tài khoản",
  	'pt-login': "Đăng nhập",
  	'pt-userlogout': "Đăng xuất",
  	'recentchangeslinked-toolbox': "Thay đổi liên quan",
  	'sandboxlink-portlet-label': "Viết nháp",
  	'searchsuggest-search': "Tìm kiếm Wikipedia",
  	'skin-view-history': "Xem lịch sử",
  	'skin-view-view': "Đọc",
  	'vector-anon-user-menu-pages': "Trang dành cho người dùng chưa đăng nhập",
  	'vector-languages': "Ngôn ngữ",
  	'visualeditor-ca-editsource': "Sửa mã nguồn",
  	'wikibase-dataitem': "Khoản mục Wikidata",
  	'wikibase-editlinkstitle': "Sửa liên kết giữa ngôn ngữ",
  	'wikibase-otherprojects': "Tại dự án khác",
  	aboutsite: "Giới thiệu Wikipedia",
  	contactpage: "Liên lạc",
  	contents: 'Nội dung',
  	currentevents: "Tin tức",
  	delete: "Xóa",
  	edit: "Sửa đổi",
  	help: "Trợ giúp",
  	introduction: undefined,
  	move: "Di chuyển",
  	mycontribs: "Đóng góp",
  	mypreferences: "Tùy chọn",
  	mytalk: "Tin nhắn",
  	permalink: "Liên kết thường trực",
  	portal: "Cộng đồng",
  	printableversion: "Bản để in ra",
  	purge: "Làm mới",
  	randompage: "Bài viết ngẫu nhiên",
  	recentchanges: "Thay đổi gần đây",
  	searchbutton: "Tìm kiếm",
  	sitesupport: "Quyên góp",
  	specialpages: "Trang đặc biệt",
  	tagline: "Bách khoa toàn thư mở Wikipedia",
  	talk: "Thảo luận",
  	toc: "Mục lục",
  	toolbox: "Công cụ",
  	upload: "Tải tập tin lên",
  	whatlinkshere: "Các liên kết đến đây",
    collapseMenu: "Thu gọn menu",
    pinMenuToSidebar: "Ghim menu",
    advancedTools: "Các công cụ nâng cao",
    username: "Tên_1993",
    modal: "<b>Xin nhắc lại:</b> đây là một nguyên mẫu. Hầu hết mọi thứ không hoạt động. Một số phần của giao diện có thể không được dịch sang ngôn ngữ địa phương của bạn. Hãy tập trung sự chú ý của bạn và phản hồi của bạn vào các khu vực của giao diện mà câu hỏi đặt ra. Nếu nội dung trang không tải, vui lòng làm mới trang. Cảm ơn bạn đã dành thời gian : )",
    taglineImg: '<img id="tagline" src="/img/logos/tagline-vi.svg">',
    downloadPDF: 'Tải về dưới dạng PDF',
    subpages: 'Trang con',
    pagelogs: 'Nhật ký trang',
    analysis: 'Phân tích'
  },
  zh: {
    'betafeatures-toplink': "测试",
  	'citethispage-link': "引用本页",
  	'coll-print_export': "打印/导出",
  	'cx-campaign-contributionsmenu-mytranslations': "翻译",
  	'cx-campaign-contributionsmenu-myuploads': "上传的媒体",
  	'mainpage-description': "首页",
  	'nstab-main': "条目",
  	'pageinfo-toolboxlink': "页面信息",
  	'pt-createaccount': "创建账号",
  	'pt-login': "登录",
  	'pt-userlogout': "退出",
  	'recentchangeslinked-toolbox': "相关更改",
  	'sandboxlink-portlet-label': "沙盒",
  	'searchsuggest-search': "搜索维基百科",
  	'skin-view-history': "查看历史",
  	'skin-view-view': "阅读",
  	'vector-anon-user-menu-pages': "未登录编辑者的页面",
  	'vector-languages': "语言",
  	'visualeditor-ca-editsource': "编辑源代码",
  	'wikibase-dataitem': "{{WBREPONAME}}项目",
  	'wikibase-editlinkstitle': "编辑跨语言链接",
  	'wikibase-otherprojects': "在其他项目中",
  	aboutsite: "关于维基百科",
  	contactpage: "联络页面",
  	contents: undefined,
  	currentevents: "新闻动态",
  	delete: "删除",
  	edit: "编辑本页",
  	help: "帮助",
  	introduction: undefined,
  	move: "移动",
  	mycontribs: "贡献",
  	mypreferences: "参数设置",
  	mytalk: "留言",
  	permalink: "固定链接",
  	portal: "维基社群",
  	printableversion: "打印页面",
  	purge: "刷新",
  	randompage: "随机条目",
  	recentchanges: "最近更改",
  	searchbutton: "搜索",
  	sitesupport: "资助维基百科",
  	specialpages: "特殊页面",
  	tagline: "维基百科，自由的百科全书",
  	talk: "讨论",
  	toc: "目录",
  	toolbox: "工具",
  	upload: "上传文件",
  	whatlinkshere: "链入页面",
    collapseMenu: "折疊菜單",
    pinMenuToSidebar: "固定菜單",
    advancedTools: "高級工具",
    username: "姓名_1993",
    downloadPDF: '下载为PDF',
    modal: "<b>提醒</b>：這是一個原型。 大多數事情都不工作。 界面的某些部分可能不會轉換為您的本地語言。 請注意您對問題詢問的界面區域的關注和反饋。 如果頁面內容未加載，請刷新頁面。 感謝您的時間 : )",
    wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-zh.svg">',
    taglineImg: '<img id="tagline" src="/img/logos/tagline-zh.svg">'
  }
}

// add commas to end of translatedStrings
// str = str.replace(/(?:\r\n|\r|\n)/g, ',');
// beautify via https://codebeautify.org/jsviewer

// add manual strings
// replace {{SITENAME}}
// replace {{WBREPONAME}} (Wikidata)


var whatever = {
  collapseMenu: "Свернуть меню",
  pinMenuToSidebar: "Anclar menú a la barra lateral",
  advancedTools: "Herramientas avanzadas",
  username: "nombre_1993",
  downloadPDF: 'Tải về dưới dạng PDF',
  modal: "<b>Reminder</b>: this is a prototype. Most things do not work. Some parts of the interface might not be translated into your local language. Please focus your attention and your feedback on the areas of the interface that the questions ask about. If the page content is not loading, please refresh the page. Thank you for your time : )",
  wordmarkImg: '<img id="tagline" src="/img/logos/wordmark-uk.svg">',
  taglineImg: '<img id="tagline" src="/img/logos/tagline-uk.svg">'
}
